### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by CrazyFlasher** [haxeui/haxeui-heaps#23]
Using this sample
https://github.com/haxeui/component-examples/tree/master/buttons

http://188.166.108.195/testui/ - build

Clicking “Add button” doesn’t do anything, except console log:
```
haxe/ui/core/Component.hx:1394: Problem executing scriptlet: EUnknownVariable(add)
```
Took latest git of heaps, haxeui-code and haxeui-heaps
Build script:
```
-cp src
-main Main

-lib haxeui-core
-lib haxeui-heaps
-lib heaps

-js build/html5/Main.js
```

**Comment by ianharrigan** [comment]
Hmmm, yeah, i can reproduce it... dont quite get it though as the "add" function is certainly there in the script...

**Comment by ianharrigan** [comment]
Whats even more strange is it seems this is a heaps only issue - same app works fine on other backends... its almost as if heaps "strips" the script part... which doesnt make any sense

**Comment by ianharrigan** [comment]
This should be fixed now in latest haxeui-heaps (might want to grab core too anyway)... there was actually a bug with the initialsation order in haxeui-heaps that caused this... Long story short, the component was saying "im ready" too early 

If that works for you, can you close this? 

Cheers,
Ian

**Comment by CrazyFlasher** [comment]
It works now, thank you!
