### ISSUE TITLE
AppImpl missing on backend?

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-heaps#3]
git/haxe/ui/HaxeUIApp.hx:4: characters 8-31 : Type not found : haxe.ui.backend.AppImpl

[HaxeUITest.zip](https://github.com/haxeui/haxeui-heaps/files/4523941/HaxeUITest.zip)

**Comment by ianharrigan** [comment]
Ah, good catch... this is because the way ive been testing haxeui-heaps has been to use it in a existing heaps application (rather than use a haxeui app) - will fix this.
