### ISSUE TITLE
Textarea doesnt except entry 

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-heaps#34]
I'm in git everything. Just after haxeui 1.4 release

Put a Textarea in xml. Compile to heaps and try to enter text  
In this video I am smashing on the keys....suddenly some text appears right at the end???
![noentry huh](https://user-images.githubusercontent.com/2074385/153735572-2af5db17-b205-4edc-bc65-1a640952ff54.gif)

after playing with it more it appears key entry occurs when mouse is not over the textarea but another texfield or the main app? weird

[HeapsTest.zip](https://github.com/haxeui/haxeui-heaps/files/8054848/HeapsTest.zip)

**Comment by hoseyjoe** [comment]
In this gif I am continually typing.  You can see the characters appear when the cursor is over text field or empty app. I clipped off the part when the mouse is over the textarea, but it doesnt get entered then
![noentry2](https://user-images.githubusercontent.com/2074385/154402110-78f1cc65-fd0f-4f5c-849a-ba8e91d43aa4.gif)

**Comment by ianharrigan** [comment]
This should be fixed now
