### ISSUE TITLE
Commit in core broke haxeui-html, haxeui-heaps

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-heaps#9]
Commit "Clean" 5bc0debf521dea8a3c7d600946d2699189d87f6b changes project appearance from

"verticalvirtuallayout fix" commit  
![image](https://user-images.githubusercontent.com/2074385/80892823-e2aed580-8c81-11ea-8acc-405692a80455.png)

To "Clean" commit  
![image](https://user-images.githubusercontent.com/2074385/80892789-a4191b00-8c81-11ea-91d2-7f1f75958485.png)

[HaxeUITest.zip](https://github.com/haxeui/haxeui-heaps/files/4568999/HaxeUITest.zip)

**Comment by hoseyjoe** [comment]
I meant to put this in core issues. sorry

**Comment by ianharrigan** [comment]
OK, this should be fixed now.

**Comment by hoseyjoe** [comment]
fixed
